Repository GodotModding/godot-mod-loader, pull requests merged in 2023-04, with the labels that each got.

#207 feat: Option to skip deprecated fatal error
  addons/mod_loader/api/deprecated.gd
  addons/mod_loader/classes/options_profile.gd
  addons/mod_loader/mod_loader_store.gd
Labels: enhancement

#203 feat: mod reloading
  addons/mod_loader/mod_loader.gd
Labels: enhancement

#208 refactor: Move main mod API funcs to `ModLoaderMod`, from `ModLoader`
  addons/mod_loader/api/mod.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_store.gd
Labels: refactor / cleanup, breaking

#209 Add PR Dependency Check GitHub Action
  .github/workflows/main.yml
Labels: enhancement

#213 ci: add PR dependency check GitHub action
  .github/workflows/main.yml
Labels: enhancement

#215 fix: :bug: check if a mod `is_loadable`
  addons/mod_loader/mod_loader.gd
Labels: bug

#205 refactor: :recycle: Logging
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/deprecated.gd
  addons/mod_loader/api/godot.gd
  addons/mod_loader/api/log.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/api/third_party/steam.gd
  addons/mod_loader/classes/mod_data.gd
  addons/mod_loader/classes/mod_manifest.gd
  addons/mod_loader/classes/options_profile.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: enhancement, refactor / cleanup, breaking

#210 feat: ✨ Added `only_once` parameter to all log funcs
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/log.gd
Labels: enhancement

#211 refactor: :recycle: created *setup_log.gd* and setup_utils.gd*
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/setup/setup_log.gd
  addons/mod_loader/setup/setup_utils.gd
Labels: refactor / cleanup

#216 test: :white_check_mark: tests for manifest validation
  test/Unit/test_manifest_validation.gd
Labels: test

#218 refactor: :recycle: Move `mod_data` `ModLoader` -> `ModLoaderStore`
  addons/mod_loader/api/config.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: refactor / cleanup, breaking

#220 refactor: :recycle: Move `mod_load_order` to `ModLoaderStore`
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: refactor / cleanup

#224 refactor: ♻️ move remaining vars to `ModLoaderStore`
  addons/mod_loader/api/mod.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: refactor / cleanup

#226 refactor: ♻️ Split up `ModLoaderUtils`
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/api/third_party/steam.gd
  addons/mod_loader/classes/mod_data.gd
  addons/mod_loader/internal/cli.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/godot.gd
  addons/mod_loader/internal/mod_loader_utils.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: refactor / cleanup

#222 refactor: ♻️ added `ModLoaderDependency` Class
  addons/mod_loader/internal/dependency.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: refactor / cleanup

#225 refactor: ♻️ added `ModLoaderScriptExtension` Class
  addons/mod_loader/api/mod.gd
  addons/mod_loader/classes/script_extension_data.gd
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: refactor / cleanup

#214 feat: ✨ Add user profiles
  addons/mod_loader/api/profile.gd
  addons/mod_loader/classes/mod_data.gd
  addons/mod_loader/classes/options_profile.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: enhancement

#232 style: ✏️ rename funcs to match naming convention
  addons/mod_loader/classes/mod_data.gd
  addons/mod_loader/internal/cli.gd
  addons/mod_loader/internal/dependency.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/godot.gd
  addons/mod_loader/internal/mod_loader_utils.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/setup/setup_utils.gd
Labels: refactor / cleanup

#230 refactor: 🚚 Moved and renamed `ModLoaderSteam`
  addons/mod_loader/internal/third_party/steam.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
Labels: refactor / cleanup

#233 refactor: ♻️ move consts from `ModLoader` to `ModLoaderStore`
  addons/mod_loader/api/mod.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: refactor / cleanup, breaking

#234 fix: 🐛 wrong `UNPACKED_DIR` reference
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/mod_loader.gd
Labels: bug

#235 fix: :bug: fix wrong function call
  addons/mod_loader/api/mod.gd
  addons/mod_loader/internal/script_extension.gd
Labels: bug
