Repository GodotModding/godot-mod-loader, pull requests merged in 2023-06, with the labels that each got.

#255 refactor: 🚚 move funcs out of ModLoader
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/internal/third_party/steam.gd
  addons/mod_loader/mod_loader.gd
Labels: refactor / cleanup

#252 refactor: ♻️ Ignore hidden directories
  addons/mod_loader/mod_loader.gd
Labels: enhancement, refactor / cleanup

#261 refactor: :recycle: remove `incompatibilities` from required keys
  addons/mod_loader/classes/mod_manifest.gd
Labels: refactor / cleanup

#259 fix: :pencil2: removed reference to manifest in error message
  addons/mod_loader/internal/mod_loader_utils.gd
Labels: bug

#258 fix: 🐛 added deprecation for `mod_data`
  addons/mod_loader/api/mod.gd
  addons/mod_loader/mod_loader.gd
Labels: bug

#264 feat: ✨ option to allow autoload placement anywhere
  addons/mod_loader/classes/options_profile.gd
  addons/mod_loader/internal/godot.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
Labels: bug, enhancement

#260 refactor: :recycle: store Profile object instead of profile name
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/profile.gd
  addons/mod_loader/classes/mod_data.gd
  addons/mod_loader/classes/mod_user_profile.gd
  addons/mod_loader/mod_loader_store.gd
Labels: enhancement, refactor / cleanup

#265 chore: :pencil2: renamed `classes` dir to `resources`
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/options/options.tres
  addons/mod_loader/options/profiles/current.tres
  addons/mod_loader/options/profiles/default.tres
  addons/mod_loader/options/profiles/disable_mods.tres
  addons/mod_loader/options/profiles/production_no_workshop.tres
  addons/mod_loader/options/profiles/production_workshop.tres
  addons/mod_loader/resources/mod_config.gd
  addons/mod_loader/resources/mod_data.gd
  addons/mod_loader/resources/mod_manifest.gd
  addons/mod_loader/resources/mod_user_profile.gd
  addons/mod_loader/resources/options_current.gd
  addons/mod_loader/resources/options_profile.gd
  addons/mod_loader/resources/script_extension_data.gd
Labels: refactor / cleanup

#270 fix: :bug: added a check if `current_user_profile` is `null`
  addons/mod_loader/api/config.gd
Labels: bug

#269 fix: :bug: removed `dir_exists()` check
  addons/mod_loader/internal/path.gd
  addons/mod_loader/resources/mod_manifest.gd
Labels: bug

#272 chore: :arrow_up: update version const for v6
  addons/mod_loader/mod_loader_store.gd
Labels: release

#275 fix: :bug: wrong steam workshop directory path
  addons/mod_loader/internal/third_party/steam.gd
Labels: bug

#276 fix: always use warnings for deprecations in standalone builds
  addons/mod_loader/api/deprecated.gd
Labels: bug

#278 fix: :bug: log stack only saved for `logged_messages.all`
  addons/mod_loader/api/log.gd
Labels: bug

#279 docs: 📝 Rewrote API class comments
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/deprecated.gd
  addons/mod_loader/api/log.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/api/profile.gd
Labels: documentation

#277 fix: Transitive Comparator for script sorting
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/mod_loader_store.gd
Labels: bug

#283 refactor: :truck: Moved methods handling mod state
  addons/mod_loader/api/mod.gd
  addons/mod_loader/api/mod_manager.gd
  addons/mod_loader/mod_loader_setup.gd
Labels: refactor / cleanup

#291 fix: :bug: added missing `static`
  addons/mod_loader/api/mod_manager.gd
Labels: bug, breaking

#284 chore: :memo: updated readme with more details
  README.md
Labels: documentation

#292 style: :art: added and removed whitespace
  addons/mod_loader/api/mod.gd
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/mod_loader_store.gd
Labels: style

#293 fix: :bug: `current_user_profile` reference to `user_profiles`
  addons/mod_loader/api/profile.gd
Labels: bug

#300 fix: :bug: Fix ModLoaderUtils log deprecation using `ModLoader.*`
  addons/mod_loader/internal/mod_loader_utils.gd
Labels: bug

#297 refactor: :recycle: reworked disabling mods via user profile
  addons/mod_loader/api/profile.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/resources/mod_data.gd
Labels: bug, refactor / cleanup, breaking

#298 refactor: ♻️ reworked mod uninstall detection
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/internal/third_party/steam.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/mod_data.gd
Labels: bug, enhancement

#301 chore: 📝added Discord and Issues link to readme
  README.md
Labels: documentation

#303 fix: 🐛 check if mod zip is structured correctly
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/path.gd
Labels: bug

#304 refactor: :recycle: lowered the log level from fatal to error
  addons/mod_loader/internal/path.gd
Labels: refactor / cleanup

#305 chore: :arrow_up: update version const for v6.0.1
  addons/mod_loader/mod_loader_store.gd
Labels: release

#302 v6.0.1
  README.md
  addons/mod_loader/api/mod.gd
  addons/mod_loader/api/mod_manager.gd
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/mod_loader_utils.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/internal/third_party/steam.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/mod_data.gd
Labels: release

#307 fix: :bug: `ModData` init and uninstall detection
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/mod_loader.gd
Labels: bug

#308 refactor: :recycle: unique ids `optional_dependencies` - `dependencies`
  addons/mod_loader/resources/mod_manifest.gd
Labels: validation, breaking

#309 chore: :arrow_up: update version const for v6.0.2
  addons/mod_loader/mod_loader_store.gd
Labels: release

#312 refactor: :recycle: unique ids `load_before` - `incompatibilities`
  addons/mod_loader/resources/mod_manifest.gd
Labels: validation, breaking
