Repository GodotModding/godot-mod-loader, pull requests merged in 2023-03, with the labels that each got.

#148 Workshop Support
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_utils.gd
  addons/mod_loader/options/classes/options_profile.gd
  addons/mod_loader/options/profiles/current.tres
  addons/mod_loader/options/profiles/default.tres
  addons/mod_loader/options/profiles/disable_mods.tres
  addons/mod_loader/options/profiles/production_no_workshop.tres
  addons/mod_loader/options/profiles/production_workshop.tres
Labels: enhancement

#155 Refactor: Move `class_name` to be before `extends`
  addons/mod_loader/classes/mod_data.gd
  addons/mod_loader/classes/mod_manifest.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: refactor / cleanup

#162 feat: :sparkles: Added `get_as_dict()` function to ModManifest Class
  addons/mod_loader/classes/mod_manifest.gd
Labels: enhancement

#159 Refactor: Move options classes + Rename options_current
  addons/mod_loader/classes/options_current.gd
  addons/mod_loader/classes/options_profile.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/options/options.tres
  addons/mod_loader/options/options_current.tres
  addons/mod_loader/options/profiles/current.tres
  addons/mod_loader/options/profiles/default.tres
  addons/mod_loader/options/profiles/disable_mods.tres
  addons/mod_loader/options/profiles/production_no_workshop.tres
  addons/mod_loader/options/profiles/production_workshop.tres
Labels: refactor / cleanup

#157 API: Move Config to a dedicated class
  addons/mod_loader/api/config.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
Labels: refactor / cleanup

#160 Options: Add option to skip mods by mod ID
  addons/mod_loader/classes/options_profile.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/options/profiles/current.tres
  addons/mod_loader/options/profiles/default.tres
  addons/mod_loader/options/profiles/disable_mods.tres
  addons/mod_loader/options/profiles/production_no_workshop.tres
  addons/mod_loader/options/profiles/production_workshop.tres
Labels: enhancement

#163 refactor: :recycle: ModManifest - Added type checks
  addons/mod_loader/classes/mod_manifest.gd
Labels: enhancement, validation

#164 refactor: ♻️ Added compatible_mod_loader_version to manifest data
  addons/mod_loader/classes/mod_manifest.gd
Labels: enhancement

#168 fix: :pencil2: fix typo hypen -> hyphen
  addons/mod_loader/classes/mod_manifest.gd
Labels: enhancement

#170 refactor: :recycle: split off dep and inc validation function
  addons/mod_loader/classes/mod_manifest.gd
Labels: validation

#175 feat: :sparkles: ModManifest - Added `to_json()` function
  addons/mod_loader/classes/mod_manifest.gd
Labels: enhancement

#172 feat: ✨ ModLoaderStore: New singleton to store data
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/godot.gd
  addons/mod_loader/api/third_party/steam.gd
  addons/mod_loader/classes/options_profile.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/mod_loader_utils.gd
  addons/mod_loader/options/profiles/current.tres
  addons/mod_loader/options/profiles/default.tres
  addons/mod_loader/options/profiles/disable_mods.tres
  addons/mod_loader/options/profiles/production_no_workshop.tres
  addons/mod_loader/options/profiles/production_workshop.tres
Labels: enhancement, refactor / cleanup

#176 fix: ✏️ Fix typo: `improt` -> `import`
  addons/mod_loader/mod_loader.gd
Labels: bug

#177 style: :art: Add `\t` indent to `JSON.print()`
  addons/mod_loader/classes/mod_manifest.gd
Labels: enhancement

#182 refactor: :recycle: Move utility funcs out of *mod_manifest.gd*
  addons/mod_loader/classes/mod_manifest.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: refactor / cleanup

#183 fix: :bug: circular dependency check
  addons/mod_loader/mod_loader.gd
Labels: bug

#184 fix: :bug: continue check if circular dep is detected
  addons/mod_loader/mod_loader.gd
Labels: bug

#185 feat: :sparkles: added load_before
  addons/mod_loader/classes/mod_manifest.gd
  addons/mod_loader/mod_loader.gd
Labels: enhancement

#188 feat: :sparkles: Added optional dependencies
  addons/mod_loader/classes/mod_manifest.gd
  addons/mod_loader/mod_loader.gd
Labels: enhancement

#174 fix: ♻️ ModID in `dependencies` and `incompatibilities`
  addons/mod_loader/classes/mod_manifest.gd
Labels: enhancement, validation

#191 refactor: :recycle: split validation functions
  addons/mod_loader/classes/mod_manifest.gd
Labels: validation, refactor / cleanup

#193 refactor: :recycle: `validate_distinct_mod_ids_in_arrays()`
  addons/mod_loader/classes/mod_manifest.gd
Labels: bug, validation, refactor / cleanup

#194 feat: ✨ Added validation for load_before
  addons/mod_loader/classes/mod_manifest.gd
Labels: validation

#196 refactor: :recycle: Check for valid mod ids in `load_before`
  addons/mod_loader/classes/mod_manifest.gd
Labels: validation

#199 refactor: :recycle: changed mod config dir path to `user://configs`
  addons/mod_loader/mod_loader_utils.gd
Labels: refactor / cleanup

#195 feat: added _reset_extension
  addons/mod_loader/mod_loader.gd
Labels: enhancement

#198 feat: added _remove_extension
  addons/mod_loader/mod_loader.gd
Labels: enhancement

#201 fix: :bug: self setup chicken and egg problem
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: bug

#202 Fix mod id validation
  addons/mod_loader/classes/mod_manifest.gd
Labels: validation
