Repository GodotModding/godot-mod-loader, pull requests merged in 2023-02, with the labels that each got.

#95 Fix global class registration
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: bug

#96 Assert modlaoder is first autoload
  addons/mod_loader/mod_loader.gd
Labels: validation

#91 Validate dependencies and incompatibilities
  addons/mod_loader/mod_manifest.gd
Labels: validation

#94 --only-setup cli arg
  addons/mod_loader/mod_loader_setup.gd
Labels: enhancement, installation

#100 store log backups and rotate them like godot
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: enhancement

#104 Utils for ModLoader autoload position
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: enhancement, installation

#105 Check modloader autoload position on setup
  addons/mod_loader/mod_loader_setup.gd
Labels: enhancement, installation

#107 Downgrade the missing `mods` dir error to a warning
  addons/mod_loader/mod_loader.gd
Labels: validation

#110 ✔ added checks for override.cfg setup
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
Labels: bug, enhancement, installation

#118 Validate file exists for `add_translation_from_resource`
  addons/mod_loader/mod_loader.gd
Labels: validation

#112 v4.2.0
  addons/mod_loader/mod_data.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_utils.gd
  addons/mod_loader/mod_manifest.gd
  addons/mod_loader/run.gd
  addons/mod_loader/vendor/godotpcktool/LICENSE
  addons/mod_loader/vendor/godotpcktool/godotpcktool.exe
Labels: release

#120 v5.0.1 resource_path validation for add_translation_from_resource(resource_path: String)
  addons/mod_loader/mod_loader.gd
Labels: validation, release

#123 v5.0.1
  addons/mod_loader/mod_data.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_utils.gd
  addons/mod_loader/mod_manifest.gd
  addons/mod_loader/run.gd
  addons/mod_loader/vendor/godotpcktool/LICENSE
  addons/mod_loader/vendor/godotpcktool/godotpcktool.exe
Labels: release

#130 refactor: :recycle: Added is_silent parameter to validation functions
  addons/mod_loader/mod_manifest.gd
Labels: enhancement

#134 Validation: Don't allow mods to include themselves as dependencies or incompatibilities
  addons/mod_loader/mod_manifest.gd
Labels: validation

#137 Config JSON: Swap status codes 1 and 2 (closes #131)
  addons/mod_loader/mod_loader.gd
Labels: validation

#139 Misc: Add `code_note` func, to show a helpful message in `log_fatal`
  addons/mod_loader/mod_loader_utils.gd
Labels: validation

#142 Config JSON: Add API methods for saving data
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_utils.gd
Labels: enhancement, validation

#143 Utility: Add 2 funcs for saving data to files
  addons/mod_loader/mod_loader_utils.gd
Labels: enhancement

#149 Misc: Uncomment `code_note` code in file saving API methods
  addons/mod_loader/mod_loader_utils.gd
Labels: refactor / cleanup

#150 Move classes to their own directory
  addons/mod_loader/classes/mod_data.gd
  addons/mod_loader/classes/mod_manifest.gd
  addons/mod_loader/classes/script_extension_data.gd
  addons/mod_loader/mod_loader_setup.gd
Labels: refactor / cleanup

#145 ML Options: Add the groundwork for loading custom options
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/options/classes/options_current.gd
  addons/mod_loader/options/classes/options_profile.gd
  addons/mod_loader/options/options_current.tres
  addons/mod_loader/options/profiles/current.tres
  addons/mod_loader/options/profiles/default.tres
  addons/mod_loader/options/profiles/disable_mods.tres
  addons/mod_loader/options/profiles/production_no_workshop.tres
  addons/mod_loader/options/profiles/production_workshop.tres
Labels: enhancement

#138 Config JSON: Only log notice for no custom JSON once
  addons/mod_loader/mod_loader.gd
Labels: validation
