Repository GodotModding/godot-mod-loader, pull requests merged in 2023-07, with the labels that each got.

#310 v6.0.2
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/mod_manifest.gd
Labels: release

#314 feat: Implement a cache of script inheritence
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/resources/script_extension_data.gd
Labels: enhancement, performance

#323 ci: :recycle: no longer ignore the main branch
  .github/workflows/main.yml
Labels: workflows

#325 chore: :arrow_up: update version const for v6.1.0
  addons/mod_loader/mod_loader_store.gd
Labels: release

#322 v6.1.0
  .github/workflows/main.yml
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/script_extension_data.gd
Labels: release

#326 feat: add dictionary for overrides based on feature tags to options
  addons/mod_loader/api/log.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/options/options.tres
  addons/mod_loader/options/profiles/editor.tres
  addons/mod_loader/resources/options_current.gd
Labels: enhancement

#330 refactor: :recycle: demote log messages
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/file.gd
Labels: refactor / cleanup
