Repository GodotModding/godot-mod-loader, pull requests merged in 2024-11, with the labels that each got.

#408 feat: ✨ Mod Hooks
  addons/mod_loader/_export_plugin/export_plugin.gd
  addons/mod_loader/_export_plugin/plugin.cfg
  addons/mod_loader/_export_plugin/plugin.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/internal/cache.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/mod_hook_packer.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/options_profile.gd
  addons/mod_loader/restart_notification.gd
  addons/mod_loader/restart_notification.tscn
Labels: 4.x

#416 Feat zip peeking
  addons/mod_loader/_export_plugin/export_plugin.gd
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/cli.gd
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/hooks.gd
  addons/mod_loader/internal/mod_hook_packer.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/internal/third_party/steam.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_setup.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/mod_data.gd
  addons/mod_loader/resources/mod_manifest.gd
  addons/mod_loader/resources/options_profile.gd
  addons/mod_loader/restart_notification.gd
  addons/mod_loader/restart_notification.tscn
  addons/mod_loader/setup/setup_utils.gd
Labels: enhancement, 4.x

#422 refactor: use truthy values in dictionaries used as hashsets
  addons/mod_loader/internal/hooks.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
  addons/mod_loader/mod_loader_store.gd
Labels: 4.x

#423 refactor: don't inline is_func_moddable
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: 4.x

#424 refactor: :recycle: updated `hook_pre_processor` reference
  addons/mod_loader/_export_plugin/export_plugin.gd
Labels: 4.x

#421 Update Mod Hooks plugin.cfg
  addons/mod_loader/_export_plugin/plugin.cfg
Labels: 4.x

#425 fix: :bug: fixed super fixing
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: bug, 4.x

#428 style: :fire: removed `%` from hook template string
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: style, 4.x

#429 feat: disable hook check when not needed
  addons/mod_loader/_export_plugin/export_plugin.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: 4.x

#430 feat: split off verbose hook preprocessing
  addons/mod_loader/_export_plugin/export_plugin.gd
  addons/mod_loader/internal/mod_hook_packer.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: 4.x

#433 style: :pencil2: Changed `MOD_LOADER_HOOKS_START_STRING`
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: style, 4.x

#431 fix: proper logging of empty Array()
  addons/mod_loader/internal/file.gd
Labels: bug, 4.x

#435 fix: hooks argument order, hook check
  addons/mod_loader/internal/hooks.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: bug, 4.x

#440 feat: ✨ allow installing hooks from a file like extensions
  addons/mod_loader/api/hook_chain.gd
Labels: enhancement, 4.x

#469 feat: ✨ param and return manipulation for mod hooks
  addons/mod_loader/api/hook_chain.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/internal/hooks.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
  addons/mod_loader/mod_loader_setup.gd
Labels: enhancement, 4.x

#474 fix: :ambulance: remove whitespace after `_ModLoaderHooks.call_hooks`
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: refactor / cleanup, style, 4.x

#470 feat: :sparkles: support async hooks for methods using await
  addons/mod_loader/api/hook_chain.gd
  addons/mod_loader/internal/hooks.gd
Labels: 4.x

#475 feat: ✨ detect and handle hooks for async methods
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: enhancement, 4.x
