Repository GodotModding/godot-mod-loader, pull requests merged in 2024-03, with the labels that each got.

#371 fix: Fix app_id loading error
  addons/mod_loader/internal/third_party/steam.gd
Labels: bug, 4.x

#370 fix: startup crash in log.gd
  addons/mod_loader/api/log.gd
Labels: bug, 4.x

#367 fix: dependencies not loading correctly if disabled by the user profile
  addons/mod_loader/internal/dependency.gd
Labels: bug, 4.x

#368 fix: config MD5 check
  addons/mod_loader/resources/mod_manifest.gd
Labels: bug, 4.x

#366 fix: using static `DirAccess.get_open_error()` on `null`
  addons/mod_loader/internal/third_party/steam.gd
Labels: bug, 4.x

#369 feat: Allow both workshop and local mods to be loaded
  addons/mod_loader/api/deprecated.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/options_profile.gd
Labels: enhancement, 4.x

#372 fix: :bug: fix indentation in `handle_script_extensions`
  addons/mod_loader/internal/script_extension.gd
Labels: bug, 4.x

#374 feat: :sparkles: added `refresh_config_data()` and `refresh_current_c…
  addons/mod_loader/api/config.gd
Labels: enhancement, 4.x

#375 feat: :sparkles: add `has_current_config()` and `has_config()`
  addons/mod_loader/api/config.gd
Labels: enhancement, 4.x

#376 refactor: ♻️ use `has_current_config` to prevent error print
  addons/mod_loader/api/config.gd
Labels: refactor / cleanup, 4.x

#363 fix: non-static func call on `InheritanceSorting`
  addons/mod_loader/internal/script_extension.gd
Labels: bug, 4.x
