Repository GodotModding/godot-mod-loader, pull requests merged in 2024-12, with the labels that each got.

#477 docs: correct readme and add features list
  README.md
Labels: documentation

#479 docs: update tutorial links
  addons/mod_loader/api/config.gd
  addons/mod_loader/resources/mod_config.gd
Labels: documentation

#480 refactor: :pencil2: changed config dir to `"user://mod_configs"`
  addons/mod_loader/internal/path.gd
Labels: enhancement, breaking, 4.x

#482 fix: :bug: Take resource remapping into account
  addons/mod_loader/internal/file.gd
Labels: bug, 4.x

#492 fix: 🐛 match `\` and new line
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: bug, 4.x

#493 fix: :bug: check if a method is already hooked
  addons/mod_loader/internal/mod_hook_packer.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: bug, 4.x

#497 fix: :bug: don't remove new lines in `param_string`
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: bug, 4.x

#498 fix: :bug: resolved parser error because of missing return value
  addons/mod_loader/_export_plugin/export_plugin.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: bug, 4.x

#500 Feat: Logging without store
  addons/mod_loader/api/deprecated.gd
  addons/mod_loader/api/log.gd
  addons/mod_loader/mod_loader_store.gd
Labels: bug, enhancement, deprecation, 4.x
