Repository GodotModding/godot-mod-loader, pull requests merged in 2025-02, with the labels that each got.

#534 feat: per method hooks
  .gitignore
  addons/mod_loader/internal/hooks.gd
  addons/mod_loader/internal/mod_hook_packer.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
  addons/mod_loader/mod_loader_store.gd
Labels: enhancement, 4.x

#538 feat: new editor-only log type for dev hints
  addons/mod_loader/api/log.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/options_profile.gd
Labels: enhancement, 4.x

#540 refactor: :fire: removed `ModLoaderModManager`
  addons/mod_loader/api/mod_manager.gd
  addons/mod_loader/internal/script_extension.gd
  addons/mod_loader/setup/global_script_class_cache_mod_loader.cfg
Labels: refactor / cleanup, breaking, 4.x

#541 feat: :sparkles: added `load_from_unpacked` option
  addons/mod_loader/internal/path.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  addons/mod_loader/resources/options_profile.gd
Labels: enhancement, 4.x

#543 fix: :bug: log spam on tool scripts
  addons/mod_loader/internal/hooks.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/mod_loader_store.gd
  test/test_mod_hook_preprocessor/test_script_C_processed.gd
Labels: bug, 4.x

#545 fix: :bug: use `reader.get_files().has()` before 4.2
  addons/mod_loader/internal/file.gd
  addons/mod_loader/internal/godot.gd
  addons/mod_loader/internal/mod_hook_preprocessor.gd
Labels: bug, 4.x, 4.1

#542 Doc comment standardization
  .gitattributes
  .gitignore
  CONTRIBUTING.md
  README.md
  addons/mod_loader/api/config.gd
  addons/mod_loader/api/deprecated.gd
  addons/mod_loader/api/hook_chain.gd
  addons/mod_loader/api/log.gd
  addons/mod_loader/api/mod.gd
  addons/mod_loader/api/profile.gd
  addons/mod_loader/internal/path.gd
  addons/mod_loader/mod_loader.gd
  addons/mod_loader/resources/mod_user_profile.gd
  icon.png
  icon.png.import
  main.tscn
  project.godot
Labels: documentation, 4.x
